services:
  mailhog-server:
    container_name: mailhog-server
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    restart: no
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailhog-network

networks:
  mailhog-network:
    name: mailhog-network
    driver: bridge
