services:
  oracle-23ai-server:
    container_name: oracle-23ai-server
    image: gvenzl/oracle-free:latest
    platform: linux/arm64
    restart: no
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "${ORACLE_SYSTEM_PASSWORD}"
    volumes:
      - "${ORACLE_VOLUME_DIR:-./volume}/oradata:/opt/oracle/oradata"
      - "${ORACLE_VOLUME_DIR:-./volume}/oraInventory:/opt/oracle/oraInventory"
      - "${ORACLE_VOLUME_DIR:-./volume}/diag:/opt/oracle/diag"
      - "${ORACLE_VOLUME_DIR:-./volume}/audit:/opt/oracle/audit"
      - "${ORACLE_VOLUME_DIR:-./volume}/admin:/opt/oracle/admin"
      - "${ORACLE_VOLUME_DIR:-./volume}/backup:/opt/oracle/backup"
      - "${ORACLE_VOLUME_DIR:-./volume}/init.d:/etc/init.d"
      - "${ORACLE_VOLUME_DIR:-./volume}/sysconfig:/etc/sysconfig"
    networks:
      - oracle-23ai-network

networks:
  oracle-23ai-network:
    name: oracle-23ai-network
    driver: bridge