services:
  sonarqube-server:
    container_name: sonarqube-server
    image: sonarqube:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-server_temp:/opt/sonarqube/temp
      - sonarqube-server_data:/opt/sonarqube/data
      - sonarqube-server_extensions:/opt/sonarqube/extensions
      - sonarqube-server_logs:/opt/sonarqube/logs
    networks:
      - sonarqube-network

  sonarqube-postgres:
    container_name: sonarqube-postgres
    image: postgres:latest
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - sonarqube-postgres:/var/lib/postgresql
      - sonarqube-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonarqube-network

volumes:
  sonarqube-server_temp:
    name: sonarqube-server_temp
  sonarqube-server_data:
    name: sonarqube-server_data
  sonarqube-server_extensions:
    name: sonarqube-server_extensions
  sonarqube-server_logs:
    name: sonarqube-server_logs
  sonarqube-postgres:
    name: sonarqube-postgres
  sonarqube-postgres_data:
    name: sonarqube-postgres_data

networks:
  sonarqube-network:
    name: sonarqube-network
    driver: bridge
