services:
  gcp-pubsub-server:
    container_name: gcp-pubsub-server
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    platform: linux/amd64
    restart: no
    ports:
      - "8085:8085"
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    networks:
      - gcp-pubsub-network

networks:
  gcp-pubsub-network:
    name: gcp-pubsub-network
    driver: bridge
