services:
  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:latest
    platform: linux/arm64
    restart: unless-stopped
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN_USERNAME}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    volumes:
      - "${KEYCLOAK_VOLUME_DIR:-./volume}/data:/opt/keycloak/data"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
