services:
  keycloak-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:latest
    restart: no
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
