services:
  timescaledb-server:
    container_name: timescaledb-server
    image: timescale/timescaledb-ha:pg17
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "5432:5432"
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_PASSWORD: "${TIMESCALEDB_PASSWORD}"
    volumes:
      - "${TIMESCALEDB_VOLUME_DIR:-./volume}/data:/var/lib/postgresql"
      - "${TIMESCALEDB_HOME:-.}/extension.sql:/docker-entrypoint-initdb.d/extension.sql"
    networks:
      - timescaledb-network

networks:
  timescaledb-network:
    name: timescaledb-network
    driver: bridge
