services:
  debezium-connect:
    container_name: debezium-connect
    image: debezium/connect:3.0.0.Final
    platform: linux/arm64
    restart: no
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda-broker:9092"
      GROUP_ID: "debezium"
      CONFIG_STORAGE_TOPIC: "debezium_configs"
      OFFSET_STORAGE_TOPIC: "debezium_offsets"
      STATUS_STORAGE_TOPIC: "debezium_statuses"
    networks:
      - debezium-network
      - redpanda-network
      - timescaledb-network

  debezium-server:
    container_name: debezium-server
    image: debezium/server:3.0.0.Final
    platform: linux/arm64
    restart: no
    ports:
      - "8084:8080"
    environment:
      PUBSUB_EMULATOR_HOST: "gcp-pubsub-server:8085"
    volumes:
      - "${DEBEZIUM_VOLUME_DIR:-./volume}/conf/application.properties:/debezium/config/application.properties"
      - "${DEBEZIUM_VOLUME_DIR:-./volume}/data:/debezium/data"
    networks:
      - debezium-network
      - timescaledb-network
      - gcp-pubsub-network

networks:
  debezium-network:
    name: debezium-network
    driver: bridge
  redpanda-network:
    external: true
  timescaledb-network:
    external: true
  gcp-pubsub-network:
    external: true
