services:
  openfga-migrate:
    container_name: openfga-migrate
    image: openfga/openfga:latest
    restart: no
    command: migrate
    user: nonroot
    environment:
      OPENFGA_DATASTORE_ENGINE: "sqlite"
      OPENFGA_DATASTORE_URI: "file:/home/nonroot/openfga.db"
    volumes:
      - "${OPENFGA_VOLUME_DIR:-./volume}:/home/nonroot"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - openfga-network

  openfga-server:
    container_name: openfga-server
    image: openfga/openfga:latest
    restart: unless-stopped
    command: run
    user: nonroot
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    ports:
      - "8280:8080"
      - "8281:8081"
      - "3200:3000"
    environment:
      OPENFGA_DATASTORE_ENGINE: "sqlite"
      OPENFGA_DATASTORE_URI: "file:/home/nonroot/openfga.db"
      OPENFGA_LOG_FORMAT: "json"
    volumes:
      - "${OPENFGA_VOLUME_DIR:-./volume}:/home/nonroot"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - openfga-network

networks:
  openfga-network:
    name: openfga-network
    driver: bridge