services:
  postgres-server:
    container_name: postgres-server
    image: postgres:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "${POSTGRES_VOLUME_DIR:-./volume}/data:/var/lib/postgresql"
      - "${POSTGRES_HOME:-.}/extension.sql:/docker-entrypoint-initdb.d/extension.sql"
    networks:
      - postgres-network

networks:
  postgres-network:
    name: postgres-network
    driver: bridge